site_name: Jetflow
site_description: Lightweight, production-ready framework for building agentic workflows with LLMs
site_url: https://jetflow.readthedocs.io
repo_url: https://github.com/lucasastorian/jetflow
repo_name: lucasastorian/jetflow

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Guides:
      - Single Agent: single-agent.md
      - Composition: composition.md
      - Chains: chains.md
      - Streaming: streaming.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucasastorian/jetflow
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/jetflow
